services:
  postgres:
    image: postgres:15
    container_name: asset-spy-postgres
    environment:
      POSTGRES_DB: asset_spy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - asset-spy-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: asset-spy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@assetspy.com
      PGADMIN_DEFAULT_PASSWORD: assetspy123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - asset-spy-network

  redis:
    image: redis:latest
    container_name: asset-spy-redis
    ports:
      - "6379:6379"
    networks:
      - asset-spy-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  kafka-controller:
    image: bitnami/kafka:latest
    container_name: kafka-controller
    ports:
      - "9093:9093"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CONTROLLER://kafka-controller:9093
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_KRAFT_CLUSTER_ID: 3Ea9E2Zs5uwC85VCEynr8A
    volumes:
      - controller_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/9093' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 15
    networks:
      - asset-spy-network

  kafka-broker:
    image: bitnami/kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_KRAFT_CLUSTER_ID: 3Ea9E2Zs5uwC85VCEynr8A
    depends_on:
      - kafka-controller
    volumes:
      - broker_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/9092' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 15
    networks:
      - asset-spy-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-broker:9092
    depends_on:
      - kafka-broker
    restart: unless-stopped
    networks:
      - asset-spy-network

volumes:
  postgres_data:
  broker_data:
  controller_data:
  pgadmin_data:

networks:
  asset-spy-network:
    driver: bridge
